### ISSUE TITLE
Can't boot SM 7238 in MAME (bit offtopic)

### ISSUE THREAD

**Issue by mrpenguinb** [shattered/retro-bios#17]
As shattered was the one who merged some improvements for the SM7238 emulation in MAME, I'm hoping that posting this issue here can be a way to contact you.

When starting the terminal, all I get is _Ждите_  (_Wait_) and can't enter any input.
![image](https://github.com/shattered/retro-bios/assets/13060086/334466fc-e5be-425d-9490-23446c4cabfe)

The `rt11.ini` has these lines (for reference):
```
set tti 8b
set cpu 11/23+ 256K
set rl0 writeenabled
set rl0 rl02
attach -r rl0 rl0.dsk
set rl0 badblock
; SOVIETO GAMES
attach -r rl1 games.dsk
; TELNET ACCESS FROM DA SOVIETO TERMINAL
set throttle 100k
set console telnet=19200
set console pchar=37777777777
boot rl0
quit
```

How would I load a .SAV program? There's no documentation online as far as I can see.

Any help would be appreciated, sorry if this is an inappropriate method of seeking help.

**Comment by shattered** [comment]
"Wait" means that terminal is executing its self-test; this message should disappear after 10 seconds or so.

To load a .SAV program, use RUN command at RT-11 prompt ("."); see AA-M241D-TC_RT-11_Quick_Reference_Manual_Aug91.pdf and other RT-11 manuals on bitsavers.

Some games only work with an older type of terminal (15ie in MAME).

**Comment by mrpenguinb** [comment]
As soon as the "Wait" disappears, I can't enter any text, only the F3 key works.

**Comment by mrpenguinb** [comment]
> This may mean that MAME is not connecting to SIMH (-bitb option on command line may be missing, tcp ports don't match, or MAME was started before SIMH).
> 
> Try following this guide https://wiki.mamedev.org/index.php/MAME_and_SIMH

The SIMH terminal output shows that the telnet connection is successful. 
That means something else is wrong...

**Comment by shattered** [comment]
Probably a serial port speed mismatch, then -- sm7238 defaults to 19200

Try changing bitbanger config and/or sm7238 setup

**Comment by mrpenguinb** [comment]
> Probably a serial port speed mismatch, then -- sm7238 defaults to 19200
> 
> Try changing bitbanger config and/or sm7238 setup

I've set the port in rt11.ini to 19200, still no text input.

These are the parameters I use to start MAME (no other settings set other than in RT11.ini as in my original post):
`mame sm7238 -rompath . -nofilter -rs232 null_modem -bitbanger socket.127.0.0.1:19200`

**Comment by shattered** [comment]
'set console speed' is not the right place -- go into sm7238 setup menu (F3 after self-test completes), then into 3BM menu and change both send and receive port speeds to 9600.

**Comment by mrpenguinb** [comment]
> 'set console speed' is not the right place -- go into sm7238 setup menu (F3 after self-test completes), then into 3BM menu and change both send and receive port speeds to 9600.
> 
> You can also test this with vt240 emulation in MAME -- sm7238 copies its menu layout.

Changing both send and receive speeds is required every time I start up sm7238. I don't know how to make it persist after poweroff, or start the telnet connection again manually. Thank you for all the help so far.

**Comment by shattered** [comment]
I think this game requires ie15 terminal, try using that.

**Comment by mrpenguinb** [comment]
> I think this game requires ie15 terminal, try using that.
> 
> Some of the games on that disk may not work at all in SIMH, if they depend on unemulated hardware (graphics etc.)

Ah ok. I've tested the game with the ie15 terminal and it works perfectly. I was hoping it would work with the SM7238 as well.

Are the graphics unemulated for the SM7238 in SIMH? Is that why MAME gives a warning before booting the terminal?

**Comment by shattered** [comment]
Some models of sm7238 support Tektronix 4010-style vector graphics -- that's missing.

However, games generally use bitmapped graphics hardware on the host system, and SIMH doesn't emulate it.

**Comment by mrpenguinb** [comment]
> Tetris may run in sm7238 if you manually switch it to VT52 emulation mode from setup menu, but it may also require native ie15 command set, which sm7238 does not support.
> 
> Some models of sm7238 support Tektronix 4010-style vector graphics -- that's missing.
> 
> However, games generally use bitmapped graphics hardware on the host system, and SIMH doesn't emulate it.

VT52 emulation mode makes the both versions of the game work! 🎉

However, the painted/solid character (O177) which is used by TET.SAV doesn't appear, even though `set tti 8b` is set in RT11.ini. 
set tti 8b is a required parameter for ie15 to show the solid characters from SIMH (unsafe character I've been told). 
RT-11 graphic example: [TET.SAV and TETRIS.SAV](https://web.archive.org/web/20160322164802/http://pdp-11.org.ru/~form/rtgames/) 

There's probably a different setting that needs to be set in SM7238's menus...

**Comment by shattered** [comment]
Char ^O177 is a solid block only on ie15 -- I don't think there's a menu setting in sm7238 to change that...

**Comment by mrpenguinb** [comment]
> Char ^O177 is a solid block only on ie15 -- I don't think there's a menu setting in sm7238 to change that...

Whoops, I don't know what I was thinking.... 

This is more of a general question, but do you know the approximate speed of the ie15?  What should the SIMH throttle be set to in order to be accurate to an actual ie15 terminal? Right now, I've stuck with 100k.

**Comment by shattered** [comment]
I'm not sure how to actually display those.    Their location in character generator suggests you could reach them via VT52 graphics mode combined with shift-in/shift-out, but that doesn't seem to work.

Short answer: use whatever seems ok as SIMH throttle setting.

For accuracy, I think SIMH has to be modified so that console port output speed can be set to 9600, which is what the game expects.

**Comment by mrpenguinb** [comment]
Thank you for all the guidance and information. 

I think this issue can be closed now. 

Only thing left for me to do is to set the port speed to 9600 with ie15 and additionally find what CPU speed the real hardware had. Do you know of any groups/forums I could post questions at? I'll have to use google translate for Russian only forums, (not ideal).

**Comment by shattered** [comment]
ie15 defaults to 9600, so no changes are needed.

For CPU speed, pick something between 2 and 6 MHz.

Try forums at vcfed.org first; for MAME-specific questions, bannister.org and mamedev.org.   SIMH has a discussion group on groups.io.
